package com.demo.order_service.outbox;

import com.demo.order_service.models.OutboxEvent;
import com.demo.order_service.models.OutboxStatus;
import com.demo.order_service.repository.OutboxEventRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Limit;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Drains the outbox to Kafka.
 *
 * <p>This is the half of the pattern that trades a lost event for a possibly-duplicated one.
 * The order and its outbox row are already committed atomically; all that remains is getting
 * the row onto the broker, and this can retry indefinitely without risking correctness —
 * because the consumers are idempotent (Phase 4). The outbox and idempotent consumers are
 * two halves of one design, not two independent features.
 */
@Component
@Slf4j
public class OutboxPublisher {

    private final OutboxEventRepository outboxEventRepository;
    private final KafkaTemplate<String, String> kafkaTemplate;

    /**
     * Constructor written out rather than generated by Lombok, because Lombok does not copy
     * {@code @Qualifier} onto the generated parameter. Without the qualifier Spring falls
     * back to by-name resolution and picks Boot's auto-configured bean -- which is literally
     * named {@code kafkaTemplate} and serializes values as JSON, double-encoding the
     * already-serialized payload. It would wire up cleanly and be wrong at runtime.
     */
    public OutboxPublisher(
            OutboxEventRepository outboxEventRepository,
            @Qualifier("stringKafkaTemplate") KafkaTemplate<String, String> kafkaTemplate) {
        this.outboxEventRepository = outboxEventRepository;
        this.kafkaTemplate = kafkaTemplate;
    }

    @Value("${outbox.batch-size:100}")
    private int batchSize;

    @Value("${outbox.max-attempts:10}")
    private int maxAttempts;

    @Value("${outbox.send-timeout-seconds:10}")
    private long sendTimeoutSeconds;

    /**
     * Publishes pending rows, oldest first.
     *
     * <p>{@code fixedDelay}, not {@code fixedRate}: the next poll starts only after this one
     * finishes. With fixedRate a slow drain would overlap itself and two threads would
     * publish the same rows.
     */
    @Scheduled(
            fixedDelayString = "${outbox.poll-interval-ms:1000}",
            initialDelayString = "${outbox.initial-delay-ms:2000}")
    @Transactional
    public void drainOutbox() {

        List<OutboxEvent> pending = outboxEventRepository
                .findByStatusOrderByIdAsc(OutboxStatus.PENDING, Limit.of(batchSize));

        if (pending.isEmpty()) {
            return;
        }

        log.debug("Draining {} pending outbox event(s)", pending.size());

        for (OutboxEvent event : pending) {
            publish(event);
        }
    }

    private void publish(OutboxEvent event) {
        try {
            // Blocking on the broker's acknowledgement is the point. Fire-and-forget would
            // let the row be marked PUBLISHED for a send that later failed, which loses the
            // event -- exactly what the outbox exists to prevent.
            kafkaTemplate
                    .send(event.getTopic(), event.getAggregateId(), event.getPayload())
                    .get(sendTimeoutSeconds, TimeUnit.SECONDS);

            event.markPublished();

            log.info("Published outbox eventId={} to {} for order {}",
                    event.getEventId(), event.getTopic(), event.getAggregateId());

        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            event.markAttemptFailed("Interrupted while publishing", maxAttempts);

        } catch (Exception failure) {
            event.markAttemptFailed(failure.toString(), maxAttempts);

            if (event.getStatus() == OutboxStatus.FAILED) {
                // Terminal. Left in the table rather than dropped, so it can be found,
                // understood and replayed by hand.
                log.error("Giving up on outbox eventId={} after {} attempts",
                        event.getEventId(), event.getAttempts(), failure);
            } else {
                log.warn("Attempt {}/{} failed for outbox eventId={}: {}",
                        event.getAttempts(), maxAttempts, event.getEventId(),
                        failure.toString());
            }
        }
        // No explicit save: the entity is managed inside this transaction, so the state
        // change is flushed on commit.
    }
}
